services:
  postgres:
    image: postgres:16-alpine
    container_name: telegram-agent-db-prod
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: telegram_agent
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres}"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: telegram-agent-app
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/telegram_agent
      NODE_ENV: production
    volumes:
      - ./.claude.json:/home/appuser/.claude.json
      - ./.claude:/home/appuser/.claude

  scheduler:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: telegram-agent-scheduler
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/telegram_agent
      NODE_ENV: production
    command: ["node", "dist/scheduler.js"]
    volumes:
      - ./.claude.json:/home/appuser/.claude.json
      - ./.claude:/home/appuser/.claude

volumes:
  postgres_data_prod:
    driver: local

